### ISSUE TITLE
Any chance it is compatible with larastan?

### ISSUE THREAD

**Issue by mreduar** [datomatic/laravel-enum-helper#2]
Hi, first of all great package I was watching it and it is quite useful.

As soon as I installed and implemented it I realized that larastan does not detect that the magic methods return the correct data and gives an error of:
`Call to an undefined static method App\Enums\ActivityLogType::NEW_COMMENT()`
In my case my Trait is this

```php
<?php

namespace App\Enums;

use Datomatic\LaravelEnumHelper\LaravelEnumHelper;

enum ActivityLogType
{
    use LaravelEnumHelper;

    case NEW_COMMENT;
}
```

I know that this error is more on larastan's side than on the package side, but I would like to ask if it is possible to solve it from the package side.

**Comment by wit3** [comment]
php docblock doesn't solve the problem?

**Comment by mreduar** [comment]
> php docblock doesn't solve the problem?

Do you mean that I make a php docblock in each call I make to the enum in all my application?
Like 
```php
/** @var string */
ActivityLogType::NEW_COMMENT()
```

**Comment by wit3** [comment]
try this

```php
<?php

namespace App\Enums;

use Datomatic\LaravelEnumHelper\LaravelEnumHelper;

/**
 * @method static self NEW_COMMENT()
 */
enum ActivityLogType
{
    use LaravelEnumHelper;

    case NEW_COMMENT;
}
```

**Comment by trippo** [comment]
Yes, you must define explicitly the methods with PHP Doc on the enum class file.

You can see the test enum examples: https://github.com/datomatic/laravel-enum-helper/blob/main/tests/Support/Enums/Status.php

```php
use Datomatic\LaravelEnumHelper\LaravelEnumHelper;

/**
 * @method static string pending()
 * @method static string accepted()
 * @method static string discarded()
 * @method static string noResponse()
 */
enum Status
{
    use LaravelEnumHelper;

    case PENDING;

    case ACCEPTED;

    case DISCARDED;

    case NO_RESPONSE;
}
```
